### ISSUE TITLE
Beginning Research

### ISSUE THREAD

**Issue by megangaw** [HT-M-L/web-app#4]
Complete all research on final idea for Freelance app 
- [ ] 3 personas 
- [ ] background research
- [ ] ask at least 3 freelancers what they would like to see in an organizational app
- [ ] Target audience:** Who will use your app? Be specific. Personas are encouraged.

- [ ]  **Website goals & value proposition:** What is your app trying to do? How is it trying to do that? Why?

- [ ]  **Competitive analysis:** Find competitors; What do they do well? What do they do poorly?

**Comment by sashatran95** [comment]
I'll do the asking 3 freelancers and finding target audience.
