### ISSUE TITLE
UX Goals

### ISSUE THREAD

**Issue by laurenberg** [HT-M-L/web-app#9]
| | 0 points | 1 points | 2 points | 3 points |
| --- | --- | --- | --- | --- |
| **Accessibility** | No considerations | Added some alt attributes, nothing else | Just the basics: alt attributes, roles | Accessibility is well considered and tested |
| **Responsiveness** | Barely started | Indentation is barely existent, lots of validation errors, very poor semantics | Decent indentation, just a couple validation errors, decent semantics | Well indented, fully valid, good semantics |
| **Attractive** | Barely started | Indentation is barely existent, lots of validation errors, very poor semantics | Decent indentation, just a couple validation errors, decent semantics | Well indented, fully valid, good semantics |
| **Minimal** | Barely started | Indentation is barely existent, lots of validation errors, very poor semantics | Decent indentation, just a couple validation errors, decent semantics | Well indented, fully valid, good semantics |
| **Usability** | Barely started | Indentation is barely existent, lots of validation errors, very poor semantics | Decent indentation, just a couple validation errors, decent semantics | Well indented, fully valid, good semantics |
| **Comprehensiveness** | Barely started | Indentation is barely existent, lots of validation errors, very poor semantics | Decent indentation, just a couple validation errors, decent semantics | Well indented, fully valid, good semantics |

**Comment by sashatran95** [comment]
| | 0 points | 1 points | 2 points | 3 points |
| --- | --- | --- | --- | --- |
| **Accessibility** | | | Needed to change some headings and add another page in the "Create" pages. |
| **Responsiveness** || Only desktop sizes created. |
| **Attractive** |||| For a rough prototype it looks pretty great. |
| **Minimal** | ||| Our approach has been minimal throughout design and it shows. |
| **Usability** | | Busy week left us unable to test with a designer audience, a lot of our non-designer roommates/boyfriends/parents didn't even know they were looking at a website. |
| **Comprehensiveness** | ||| Very comprehensive and easy to use. |
